### ISSUE TITLE
一处翻译改进,  异常-->例外

### ISSUE THREAD

**Issue by zhoujin7** [pingfangx/java-tutorials-in-chinese#1]
https://pingfangx.github.io/java-tutorials/collections/interfaces/queue.html

有一些地方, 异常-->例外

**异常**情况包括优先级队列
**例外**情况包括优先级队列

LinkedList 实现是一个**异常**
LinkedList 实现是一个**例外**

**Comment by pingfangx** [comment]
感谢反馈，已经修改并更新了。
感谢你作为第一个反馈的读者，我之前认为肯定没人看呢。
