### ISSUE TITLE
传递引用数据类型实参 一节的翻译建议

### ISSUE THREAD

**Issue by Tentabrella** [pingfangx/java-tutorials-in-chinese#2]
https://pingfangx.github.io/java-tutorials/java/javaOO/arguments.html
原文是
Reference data type parameters, such as objects, are also passed into methods by value. 
引用数据的类型形参（如对象）也 通过值 传递到方法中
Reference data type 应该是修饰parameter的，毕竟参数的数据类型可分为基本数据类型或引用数据类型，因此可能翻译成”引用数据类型的形参“会更好？

**Comment by pingfangx** [comment]
感谢您的反馈，我已作出修改，可查阅。
有以下注意点：
1. 前文提到，参数可以使用基本数据类型或引用数据类型，在实践中，我们也经常简称基本类型、引用类型。因此对于参数就是基本类型参数、引用类型参数，“的”字就直接省略了（和小节的标题一致）。
2. 虽然有时候我们不太区分实参形参，统一称为参数，但在此参数一节，还是应该区分的。结合上下文，这里是调用方法时传入的实际值，所以应该是实参 arguments，小节标题也是 arguments，但原文为形参 parameters，我加了译者注。
3. 值传递可以和 C++ 引用传递作比较。

再次感谢反馈，当初翻译时是边读边译，虽然有第二篇重读修改了部分翻译，但可能还是有不少翻译不当的地方，有任何问题欢迎继续讨论交流。

**Comment by Tentabrella** [comment]
谢谢你的回复，学到了很多
